/// <reference path="../pb_data/types.d.ts" />
migrate(
  (app) => {
    const collection = new Collection({
      createRule: null,
      deleteRule: null,
      fields: [
        {
          autogeneratePattern: '[a-z0-9]{15}',
          hidden: false,
          id: 'text3208210256',
          max: 15,
          min: 15,
          name: 'id',
          pattern: '^[a-z0-9]+$',
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: 'text',
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text3616895705',
          max: 0,
          min: 0,
          name: 'model',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: true,
          system: false,
          type: 'text',
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text475199832',
          max: 0,
          min: 0,
          name: 'brand',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: true,
          system: false,
          type: 'text',
        },
        {
          hidden: false,
          id: 'select2363381545',
          maxSelect: 1,
          name: 'type',
          presentable: false,
          required: false,
          system: false,
          type: 'select',
          values: ['Sedan', 'SUV', 'Sport', 'Electric', 'Truck', 'Van'],
        },
        {
          hidden: false,
          id: 'number1682084150',
          max: null,
          min: null,
          name: 'rentPerDay',
          onlyInt: false,
          presentable: false,
          required: true,
          system: false,
          type: 'number',
        },
        {
          hidden: false,
          id: 'file3760176746',
          maxSelect: 99,
          maxSize: 0,
          mimeTypes: ['image/jpeg', 'image/webp', 'image/png'],
          name: 'images',
          presentable: false,
          protected: false,
          required: false,
          system: false,
          thumbs: [],
          type: 'file',
        },
        {
          hidden: false,
          id: 'file3643947270',
          maxSelect: 1,
          maxSize: 0,
          mimeTypes: ['image/jpeg', 'image/png', 'image/webp'],
          name: 'heroImage',
          presentable: false,
          protected: false,
          required: false,
          system: false,
          thumbs: [],
          type: 'file',
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text2010685608',
          max: 0,
          min: 0,
          name: 'discription',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: true,
          system: false,
          type: 'text',
        },
        {
          hidden: false,
          id: 'select2063623452',
          maxSelect: 1,
          name: 'status',
          presentable: false,
          required: false,
          system: false,
          type: 'select',
          values: ['Available', 'In Maintenance', 'Out of Service'],
        },
        {
          convertURLs: false,
          hidden: false,
          id: 'editor1542800728',
          maxSize: 0,
          name: 'notes',
          presentable: false,
          required: false,
          system: false,
          type: 'editor',
        },
        {
          hidden: false,
          id: 'number3145888567',
          max: 2027,
          min: 1990,
          name: 'year',
          onlyInt: true,
          presentable: false,
          required: true,
          system: false,
          type: 'number',
        },
        {
          hidden: false,
          id: 'bool2165939997',
          name: 'isFeuterd',
          presentable: false,
          required: false,
          system: false,
          type: 'bool',
        },
        {
          hidden: false,
          id: 'autodate2990389176',
          name: 'created',
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: false,
          type: 'autodate',
        },
        {
          hidden: false,
          id: 'autodate3332085495',
          name: 'updated',
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: false,
          type: 'autodate',
        },
      ],
      id: 'pbc_2999614116',
      indexes: [],
      listRule: null,
      name: 'cars',
      system: false,
      type: 'base',
      updateRule: null,
      viewRule: null,
    });

    return app.save(collection);
  },
  (app) => {
    const collection = app.findCollectionByNameOrId('pbc_2999614116');

    return app.delete(collection);
  }
);
