name: Build and Deploy to Cloudflare Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint JavaScript
        run: npm run lint:js

      - name: Lint CSS
        run: npm run lint:css

      - name: Check formatting
        run: npx prettier --check .

      - name: Build project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifact
          path: ./dist
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-lint
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-artifact
          path: ./dist

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        id: deploy
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./dist --project-name=${{ vars.CLOUDFLARE_PROJECT_NAME }} --branch=main
          wranglerVersion: '3'

      - name: Print deployment URL
        run: echo 'Deployment URL: ${{ steps.deploy.outputs.deployment-url }}'
